#!/bin/bash
#
# render-wordmark.sh "WORD" <bg-hex> <fg-hex> <theme-dir> [--cell-px N]
#
# Build an Omarchy-style Plymouth boot theme from any word.
#
#   WORD        letters and spaces only
#   bg-hex      background, e.g. '#1e1e2e'
#   fg-hex      wordmark color, e.g. '#89b4fa'
#   theme-dir   destination; receives unlock.png, preview-unlock.png, colors.toml
#   --cell-px   fixed cell width in px (default fits the word to 800px)
#
# Example:
#   ./render-wordmark.sh "AURORA" '#1e1e2e' '#89b4fa' ~/.config/omarchy/themes/aurora
#   omarchy plymouth set by theme aurora
#
# Dependencies: bash, awk, python3 with Pillow, ImageMagick (magick).

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
RASTERIZE="$SCRIPT_DIR/lib/rasterize.py"
VENDOR_ASCII="$SCRIPT_DIR/lib/omarchy-ascii-vendor"

usage() {
  sed -n '2,17p' "$SCRIPT_DIR/render-wordmark.sh" | sed 's/^# \{0,1\}//'
}

CELL_PX=""
ARGS=()
while (($# > 0)); do
  case "$1" in
  --cell-px)
    CELL_PX="${2:?--cell-px needs a value}"
    shift 2
    ;;
  --cell-px=*)
    CELL_PX="${1#--cell-px=}"
    shift
    ;;
  -h | --help)
    usage
    exit 0
    ;;
  *)
    ARGS+=("$1")
    shift
    ;;
  esac
done

if ((${#ARGS[@]} != 4)); then
  usage >&2
  exit 1
fi

WORD="${ARGS[0]}"
BG_HEX="${ARGS[1]#\#}"
FG_HEX="${ARGS[2]#\#}"
THEME_DIR="${ARGS[3]}"

if ! [[ $BG_HEX =~ ^[0-9a-fA-F]{6}$ ]]; then
  echo "Invalid background color: ${ARGS[1]} (expected #RRGGBB)" >&2
  exit 1
fi
if ! [[ $FG_HEX =~ ^[0-9a-fA-F]{6}$ ]]; then
  echo "Invalid wordmark color: ${ARGS[2]} (expected #RRGGBB)" >&2
  exit 1
fi
if [[ -z ${WORD//[[:space:]]/} ]]; then
  echo "Nothing to render." >&2
  exit 1
fi
for dep in python3 magick awk; do
  if ! command -v "$dep" >/dev/null 2>&1; then
    echo "Missing dependency: $dep" >&2
    exit 1
  fi
done
if ! python3 -c "import PIL" 2>/dev/null; then
  echo "Missing dependency: python3 Pillow (pip install pillow)" >&2
  exit 1
fi

if command -v omarchy >/dev/null 2>&1 && omarchy ascii --help >/dev/null 2>&1; then
  ASCII_CMD=(omarchy ascii)
else
  ASCII_CMD=(bash "$VENDOR_ASCII")
fi

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

if ! "${ASCII_CMD[@]}" "$WORD" >"$WORK/art.txt" 2>"$WORK/ascii.err"; then
  cat "$WORK/ascii.err" >&2
  exit 1
fi
if [[ -s $WORK/ascii.err ]]; then
  cat "$WORK/ascii.err" >&2
fi

mkdir -p "$THEME_DIR"

RASTER_ARGS=("$WORK/art.txt" "$THEME_DIR/unlock.png" "$FG_HEX")
if [[ -n $CELL_PX ]]; then
  RASTER_ARGS+=("$CELL_PX")
fi
python3 "$RASTERIZE" "${RASTER_ARGS[@]}"

PLYMOUTH_DEFAULT="${OMARCHY_PATH:-/usr/share/omarchy}/default/plymouth"
if [[ ! -d $PLYMOUTH_DEFAULT ]]; then
  echo "Omarchy default Plymouth assets not found at $PLYMOUTH_DEFAULT." >&2
  echo "unlock.png and colors.toml were written; preview-unlock.png skipped." >&2
else
  cp "$PLYMOUTH_DEFAULT/bullet.png" "$PLYMOUTH_DEFAULT/entry.png" \
    "$PLYMOUTH_DEFAULT/lock.png" "$THEME_DIR/unlock.png" "$WORK/"
  mv "$WORK/unlock.png" "$WORK/logo.png"
  for asset in bullet.png entry.png lock.png; do
    magick "$WORK/$asset" -channel RGB +level-colors "#$FG_HEX","#$FG_HEX" "$WORK/$asset"
  done

  canvas_w=1920
  canvas_h=1080
  logo_w=$(magick identify -format '%w' "$WORK/logo.png")
  logo_h=$(magick identify -format '%h' "$WORK/logo.png")
  entry_w=$(magick identify -format '%w' "$WORK/entry.png")
  entry_h=$(magick identify -format '%h' "$WORK/entry.png")
  lock_h=$(awk "BEGIN{print int($entry_h * 0.8)}")
  lock_w=$(awk "BEGIN{print int(84 * $lock_h / 96)}")
  logo_x=$(((canvas_w - logo_w) / 2))
  logo_y=$(((canvas_h - logo_h) / 2))
  entry_x=$(((canvas_w - entry_w) / 2))
  entry_y=$((logo_y + logo_h + 40))
  lock_x=$((entry_x - lock_w - 15))
  lock_y=$((entry_y + entry_h / 2 - lock_h / 2))
  bullet_y=$((entry_y + entry_h / 2 - 4))

  bullet_args=()
  for i in 0 1 2 3; do
    bx=$((entry_x + 20 + i * 12))
    bullet_args+=('(' "$WORK/bullet.png" -resize 7x7 ')' -geometry "+${bx}+${bullet_y}" -composite)
  done

  # shellcheck disable=SC2068
  magick -size ${canvas_w}x${canvas_h} "xc:#$BG_HEX" \
    "$WORK/logo.png" -geometry "+${logo_x}+${logo_y}" -composite \
    "$WORK/entry.png" -geometry "+${entry_x}+${entry_y}" -composite \
    \( "$WORK/lock.png" -resize "${lock_w}x${lock_h}" \) -geometry "+${lock_x}+${lock_y}" -composite \
    ${bullet_args[@]} \
    "$THEME_DIR/preview-unlock.png"
fi

cat >"$THEME_DIR/colors.toml" <<EOF
mode = "custom"

# Generated by omarchy-wordmark-kit: "$WORD"
background = "#$BG_HEX"
foreground = "#$FG_HEX"
accent = "#$FG_HEX"
EOF

echo "Theme ready at $THEME_DIR"
echo "Apply with: omarchy plymouth set by theme $(basename "$THEME_DIR")"
